siem-service:
  enabled: true
  image:
    repository: milume/minisiem-siem
    tag: latest
    pullPolicy: Always
  replicas: 1
  port: 8083
  env:
    dbUrl: jdbc:postgresql://minisiem-postgres:5432/minisiem
    dbUsername: minisiem
  secret:
    name: minisiem-secrets
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

incident-service:
  enabled: false

vulnerability-service:
  enabled: true
  image:
    repository: milume/minisiem-vulnerability-service
    tag: latest
    pullPolicy: Always
  replicas: 1
  port: 8081
  env:
    openctiUrl: https://placeholder.lhr.life/graphql
  secret:
    name: minisiem-secrets
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

gateway:
  enabled: true
  image:
    repository: milume/minisiem-gateway
    tag: latest
    pullPolicy: Always
  replicas: 1
  port: 8080
  redis:
    host: redis
    port: 6379
  routes:
    vulnerabilityServicePort: 8081
    incidentServicePort: 8082
    siemServicePort: 8083
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

frontend:
  enabled: true
  image:
    repository: milume/minisiem-frontend
    tag: latest
    pullPolicy: Always
  replicas: 1
  port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

redis:
  enabled: true
  image:
    repository: redis
    tag: 7-alpine
    pullPolicy: IfNotPresent
  replicas: 1
  port: 6379
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

postgres:
  enabled: true
  port: 5432
  secret:
    name: minisiem-secrets

