services:
  minisiem-postgres:
    image: postgres:16
    container_name: minisiem-postgres
    environment:
      POSTGRES_DB: minisiem
      POSTGRES_USER: minisiem
      POSTGRES_PASSWORD: minisiem
    ports:
      - "5433:5432"
    volumes:
      - minisiem_pg:/var/lib/postgresql/data

volumes:
  minisiem_pg:
