services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: minisiem
      MYSQL_USER: minisiem
      MYSQL_PASSWORD: minisiem
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
