apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  application.yml: |
    server:
      port: {{ .Values.port }}
    spring:
      application:
        name: api-gateway
      data:
        redis:
          host: {{ .Values.redis.host }}
          port: {{ .Values.redis.port }}
      cloud:
        gateway:
          routes:
            - id: vulnerability-service
              uri: http://vulnerability-service:{{ .Values.routes.vulnerabilityServicePort }}
              predicates:
                - Path=/api/cves/**
              filters:
                - RemoveRequestHeader=Origin
            - id: incident-service
              uri: http://incident-service:{{ .Values.routes.incidentServicePort }}
              predicates:
                - Path=/api/incidents/**,/api/correlation/**
              filters:
                - RemoveRequestHeader=Origin
            - id: siem-service
              uri: http://siem-service:{{ .Values.routes.siemServicePort }}
              predicates:
                - Path=/api/auth/**,/api/users/**,/api/dashboard/**,/api/acn/**,/api/audit/**,/api/falxdr/**,/api/identity/**,/api/events/**,/api/alerts/**,/api/ai/**
              filters:
                - RemoveRequestHeader=Origin
    management:
      endpoints:
        web:
          exposure:
            include: health,info
