apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  type: ClusterIP