import { useMemo, useState } from "react";
import { mockAlerts } from "../mock/alerts";
import SeverityBadge from "../components/SeverityBadge";
import type { Alert, AlertStatus } from "../models/alert";

export default function Alerts() {
    const [status, setStatus] = useState<AlertStatus | "ALL">("ALL");

    const filtered = useMemo<Alert[]>(
        () => mockAlerts.filter(a => status === "ALL" || a.status === status),
        [status]
    );

    return (
        <div>
            <h1 className="page-title">Alerts</h1>
            <p className="page-subtitle">Alerts generated by correlation rules.</p>

            <div className="filters">
                <label>
                    Status:&nbsp;
                    <select className="select" value={status} onChange={(e) => setStatus(e.target.value as any)}>
                        <option value="ALL">ALL</option>
                        <option value="OPEN">OPEN</option>
                        <option value="ACK">ACK</option>
                        <option value="CLOSED">CLOSED</option>
                    </select>
                </label>
            </div>

            <table className="table">
                <thead>
                <tr>
                    <th>Created</th>
                    <th>Title</th>
                    <th>Rule</th>
                    <th>Status</th>
                    <th>Severity</th>
                </tr>
                </thead>
                <tbody>
                {filtered.map((a) => (
                    <tr key={a.id}>
                        <td>{new Date(a.createdAt).toLocaleString()}</td>
                        <td>{a.title}</td>
                        <td>{a.sourceRule}</td>
                        <td><b>{a.status}</b></td>
                        <td><SeverityBadge severity={a.severity} /></td>
                    </tr>
                ))}
                {filtered.length === 0 ? (
                    <tr>
                        <td colSpan={5} style={{ color: "var(--muted)" }}>
                            No alerts match the current filter.
                        </td>
                    </tr>
                ) : null}
                </tbody>
            </table>
        </div>
    );
}
