apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: group-5
data:
  application.yml: |
    server:
      port: 8080
    spring:
      application:
        name: api-gateway
      data:
        redis:
          host: redis
          port: 6379
      cloud:
        gateway:
          routes:
            - id: vulnerability-service
              uri: http://vulnerability-service:8081
              predicates:
                - Path=/api/cves/**
              filters:
                - RemoveRequestHeader=Origin
            - id: incident-service
              uri: http://incident-service:8082
              predicates:
                - Path=/api/incidents/**,/api/correlation/**
              filters:
                - RemoveRequestHeader=Origin
            - id: siem-service
              uri: http://siem-service:8083
              predicates:
                - Path=/api/auth/**,/api/users/**,/api/dashboard/**,/api/acn/**,/api/audit/**,/api/falxdr/**,/api/identity/**,/api/events/**,/api/alerts/**,/api/ai/**
              filters:
                - RemoveRequestHeader=Origin
    management:
      endpoints:
        web:
          exposure:
            include: health,info
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: group-5
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: milume/minisiem-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "file:/config/application.yml"
          volumeMounts:
            - name: config
              mountPath: /config/application.yml
              subPath: application.yml
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: group-5
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
