apiVersion: v1
kind: Service
metadata:
  name: {{ include "siem-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "siem-service.labels" . | nindent 4 }}
spec:
  selector:
    app: siem-service
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  type: ClusterIP
