apiVersion: v1
kind: Secret
metadata:
  name: minisiem-secrets
  namespace: group-5
type: Opaque
stringData:
  db-password: "ZorOIrtPsbgtJlK5SvcMateeVHoa3fTb"
  jwt-secret: "lDvQ5geneWyuvDS4HbVk9l0u3N5+dc1RbeSs3yjVpmubivLhfUv/nx4JRx8L57amnDGy2L1oCjYtA8CaHT1d2g=="
  opencti-token: "7e5ae5d1-c25f-498a-b34f-fc321c91b09a"
