apiVersion: v1
kind: Secret
metadata:
  name: minisiem-secrets
  namespace: group-5
type: Opaque
stringData:
  db-password: "minisiem"
  jwt-secret: "minisiemSecretKey2024VeryLongAndSecureKeyForJWTSigning"
  opencti-token: "7e5ae5d1-c25f-498a-b34f-fc321c91b09a"
