apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minisiem-postgres-pvc
spec:
  storageClassName: csi-cinder-work
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi