apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minisiem-postgres
  namespace: group-5
spec:
  serviceName: minisiem-postgres-headless
  replicas: 1
  selector:
    matchLabels:
      app: minisiem-postgres
  template:
    metadata:
      labels:
        app: minisiem-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "minisiem"
            - name: POSTGRES_USER
              value: "minisiem"
            - name: POSTGRES_PASSWORD
              value: "minisiem"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "minisiem"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "minisiem"]
            initialDelaySeconds: 30
            periodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        storageClassName: csi-cinder-work
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
---
# Service HEADLESS — per lo StatefulSet (DNS stabile interno)
apiVersion: v1
kind: Service
metadata:
  name: minisiem-postgres-headless
  namespace: group-5
spec:
  clusterIP: None
  selector:
    app: minisiem-postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
---
# Service NORMALE con ClusterIP — usato dai microservizi via JDBC
apiVersion: v1
kind: Service
metadata:
  name: minisiem-postgres
  namespace: group-5
spec:
  selector:
    app: minisiem-postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432