apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minisiem-postgres-pvc
  namespace: group-5
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minisiem-postgres
  namespace: group-5
  labels:
    app: minisiem-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minisiem-postgres
  template:
    metadata:
      labels:
        app: minisiem-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: minisiem
            - name: POSTGRES_USER
              value: minisiem
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minisiem-secrets
                  key: db-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "minisiem"]
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: minisiem-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minisiem-postgres
  namespace: group-5
  labels:
    app: minisiem-postgres
spec:
  selector:
    app: minisiem-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
