nameOverride: "incident-service"
fullnameOverride: "incident-service"
enabled: true
image:
  repository: milume/minisiem-incident-service
  tag: latest
  pullPolicy: Always
replicas: 1
port: 8082
env:
  dbUrl: jdbc:postgresql://minisiem-postgres:5432/minisiem
  dbUsername: minisiem
secret:
  name: minisiem-secrets
resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"
