apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incident-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "incident-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "incident-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "incident-service.labels" . | nindent 8 }}
    spec:
      containers:
        - name: incident-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: DB_URL
              value: {{ .Values.env.dbUrl }}
            - name: DB_USERNAME
              value: {{ .Values.env.dbUsername }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: db-password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.port }}
            initialDelaySeconds: 90
            periodSeconds: 15