server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: vulnerability-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/cves/**

        - id: incident-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/incidents/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
