apiVersion: v1
kind: Service
metadata:
  name: minisiem-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: minisiem-postgres
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app: minisiem-postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  type: ClusterIP