apiVersion: apps/v1
kind: Deployment
metadata:
  name: minisiem-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: minisiem-postgres
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: minisiem-postgres
  template:
    metadata:
      labels:
        app: minisiem-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: db-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgres.username }}"]
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: minisiem-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minisiem-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: minisiem-postgres
spec:
  selector:
    app: minisiem-postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  type: ClusterIP